### ISSUE TITLE
There are no translations in 'en_' for key

### ISSUE THREAD

**Issue by IchordeDionysos** [marcglasberg/i18n_extension#1]
The locale `en_` does not get mapped onto `en` locale.

So when the local is `en_`, then with the translations from below it will throw the error:

`➜ There are no translations in 'en_' for "not_found".`

```dart
import 'package:i18n_extension/i18n_extension.dart';

extension Localization on String {

  static var t = Translations.byLocale("de") +
      {
        "en": {
          "not_found": "404 not found",
        },
        "de": {
          "not_found": "404 nicht gefunden",
        },
      };

  String get i18n => localize(this, t);
}
```

**Comment by marcglasberg** [comment]
Ok, I can remove the "_" and turn "en_" into "en". Easy fix, but, a question: isn't "en_" a malformed Locale? Do you  know the link to the Locale specification?

**Comment by IchordeDionysos** [comment]
@marcglasberg I did some research 🤔 
In the dart documentation the method [`Locale.toString()`](https://api.flutter.dev/flutter/dart-ui/Locale/toString.html) they say:
>it is intended to be used for debugging purposes only.  For parseable results, use [toLanguageTag](https://api.flutter.dev/flutter/dart-ui/Locale/toLanguageTag.html) instead.

However, in this package [`locale.toString()`](https://github.com/marcglasberg/i18n_extension/blob/master/lib/i18n_widget.dart#L48) is used.

I was not sure if this was the problem so I did some debugging and found out that:
`Locale("en")` is okay and will output `"en"`,
`Locale("en", "")` is not okay and will output `"en_"`, ...

A bit more info: This happens on my iOS Simulator 🤔

As this seems to be at the root a Flutter issue, I opened one over there.
https://github.com/flutter/flutter/issues/43607

**Comment by marcglasberg** [comment]
In any case it now removes extra spaces and "_", so this should be fixed.
