### ISSUE TITLE
possibly an issue with the .pot format

### ISSUE THREAD

**Issue by CodeSpartan** [marcglasberg/i18n_extension#100]
Currently, the getstrings utility puts the file name and the line number into the context field `msgctxt`
However, the specs as I understand them, state that this exact thing shouldn't be done.

Here's the [quote](https://www.gnu.org/software/gettext/manual/html_node/Contexts.html):

>The _msgctxt_ string is visible in the PO file to the translator. **You should try to make it somehow canonical and never changing. Because every time you change an _msgctxt_, the translator will have to review the translation of _msgid_.**
>
>Finding a canonical _msgctxt_ string that doesn’t change over time can be hard. **But you shouldn’t use the file name or class name** containing the _pgettext_ call – **because it is a common development task to rename a file or a class, and it shouldn’t cause translator work.**

And indeed, as soon as I change a few lines of code in my project, the getstrings utility generates new context with different line numbers, which marks the strings as needing to be reviewed in Poedit, and this does cause me additional unnecessary translator work.

Furthermore, the specs mention [an example](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html), where the line of code goes into the reference field, which is a field prefaced by `#:`

I'm new to the format, so maybe I'm misunderstanding something?
@bauerj could you weigh in, please?

**Comment by bauerj** [comment]
Thank you for bringing this up.

We were not sure about this in https://github.com/marcglasberg/i18n_extension/pull/89#issuecomment-877063585 but after re-reading the specs I'm pretty sure you're right!

Can you send in a PR that corrects this? Otherwise I will work on this next weekend.

**Comment by CodeSpartan** [comment]
Sorry, I'm only a novice at dart yet, so I'm unfortunately unable.

**Comment by bauerj** [comment]
No worries, I'll fix that then!

And sorry for the inconvenience caused by this bug.

**Comment by bauerj** [comment]
@CodeSpartan I have opened a pull request (#101) that addresses this issue. The output now looks like this:

```gettext
#: ../paperless_app\lib\routes\select_order_route.dart:56
msgid "Cancel"
msgstr ""

#: ../paperless_app\lib\delegates\paperless_text_delegate.dart:7
msgid "Confirm"
msgstr ""

#: ../paperless_app\lib\delegates\paperless_text_delegate.dart:8
msgid "Edit"
msgstr ""

```

Can you confirm if that fixes the issue you were seeing in Poedit?

**Comment by CodeSpartan** [comment]
Yes, it works as expected now. The first time, it marks absolutely all strings as "needing revision", obviously. But better to go through this once and then never worry about it again. Thanks!

**Comment by bauerj** [comment]
Thank you for testing this so quickly 😊
