### ISSUE TITLE
i18n_extension:getstrings and plural

### ISSUE THREAD

**Issue by chriscdn** [marcglasberg/i18n_extension#104]
I'm using `i18n_extension:getstrings` to generate a `.pot` file.  What I can't figure out is how to provide a plural string.   For example, in my `.dart` file I have this:

```
String message = '%d day'.plural(days)
```

This gets extracted into the `.pot` file as follows:

```
msgctxt "..."
msgid "%d day"
msgid_plural "%d day"
msgstr[0] ""
```

Ideally, I'd like the third line to be:

```
msgid_plural "%d days"
```

Is this a limitation of the parser, or am I missing something?

**Comment by marcglasberg** [comment]
Maybe @bauerj can help answering? He's the creator of the getstrings helper.

**Comment by bauerj** [comment]
Sorry, but this is currently just not implemented. See #102 (Proposal 2) for some more information.

**Comment by marcglasberg** [comment]
@bauerj Should I close this? Is it already tracked there?

**Comment by bauerj** [comment]
I guess so, yes.

**Comment by chriscdn** [comment]
If it matters, I worked around the issue with the following extension:

```dart
extension Pluralize on String {
  String pluralize(int i, String pluralText) {
    if (i == 1) {
      return this.fill([i]);
    } else {
      return pluralText.fill([i]);
    }
  }
}
```

Usage:

```dart
return "%s day".i18n.pluralize(durationDays, "%s days".i18n);
```

Thanks for the great package!
