### ISSUE TITLE
Warning: Operand of null-aware operation '!' has type 'WidgetsBinding'

### ISSUE THREAD

**Issue by meeximum** [marcglasberg/i18n_extension#107]
After upgrading to latest flutter version (2.11.0-0.0.pre.637) I get this warning?

```
/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/i18n_extension-4.2.0/lib/i18n_widget.dart:282:24: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/mySoftware/flutter/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance!.addPostFrameCallback((_) => setState(() {}));
```

**Comment by marcglasberg** [comment]
The latest, current Flutter version is `Flutter 2.10.2`. This means you are not in the stable channel. You may move to the stable channel by doing `flutter channel stable` in the terminal.

In the current stable version, `WidgetsBinding.instance` is nullable, so we must have that `!`.

**Comment by cerealexx** [comment]
Flutter 3.0.0 is now stable and this should be fixed.

**Comment by marcglasberg** [comment]
@cerealexx Please, see version: 5.0.0
