### ISSUE TITLE
"Translation key in 'en' is missing..." logs in my debug console

### ISSUE THREAD

**Issue by maginkgo** [marcglasberg/i18n_extension#119]
I try disable recording  doing:

```dart
Translations.recordMissingKeys = false;
Translations.recordMissingTranslations = false;
```
but, that don't work for me. 

Thanks for you help!

**Comment by marcglasberg** [comment]
Closing this as didn't get an answer. Feel free to provide me with a code example and I'll reopen this. Thanks!
