### ISSUE TITLE
We need to update the intl dependency

### ISSUE THREAD

**Issue by mark8044** [marcglasberg/i18n_extension#124]
Please update the intl dependency, it is holding back other packages from updating.  I tried to make a PR for it https://github.com/marcglasberg/i18n_extension/pull/123

**Comment by TamasBarta** [comment]
Yeah, I have the same issue. And apparently it also prevents me from using the latest Flutter SDK, as `flutter_localizations` depends on `0.18.0`. At least that's what I could extract from this:

```
$ flutter pub get

Resolving dependencies... (2.6s)
Because i18n_extension 6.0.0 depends on intl ^0.17.0 and no versions of i18n_extension match >6.0.0 <7.0.0, i18n_extension ^6.0.0 requires intl ^0.17.0.
So, because popjohn_frontend depends on both intl ^0.18.0 and i18n_extension ^6.0.0, version solving failed.
```

**Comment by mark8044** [comment]
@marcglasberg Please buddy 👍

**Comment by marcglasberg** [comment]
Done.

**Comment by mark8044** [comment]
You are the best!

**Comment by edwin-alvarez** [comment]
hi,I'am having same issue, the https://github.com/marcglasberg/i18n_extension/blob/master/pubspec.yaml is still pointing to [17](intl: ^0.17.0)

**Comment by marcglasberg** [comment]
@edwin-alvarez 

Yes, I downgraded the `intl` package to version `0.17.0` again, because `flutter_localizations` depends on intl `0.17.0`.

If you want `intl: 0.18.0` you have 2 options:
* Use `i18n_extension: 7.0.0`
* Do a dependency override in your `pubspec.yaml` file to force `intl: 0.18.0`.
