### ISSUE TITLE
JSONImporter and getStrings was moved outside of the lib directory.

### ISSUE THREAD

**Issue by marcglasberg** [marcglasberg/i18n_extension#126]
The `getStrings` helper depends on the `analyzer` package, which creates compatibility problems for a lot of projects. The tool is very useful, but it's creating a maintenance overhead even for people that don't use it.

It would be nice if we could run it:
* From a separate package that depends on `i18n_extension`
* From a test directory or an example directory (unlikely that would work)

In version `8.0.0` I have temporarily moved the `gestStrings` code to the test directory, so that I could move the `analyzer` dependency to the `dev_dependencies` section of the `pubspec.yaml` .

I think ideally it should be a separate project that users could add to their own `dev_dependencies` section. If that can be made into a separate package, I would link it from the `i18n_extension` documentation.

@bauerj

**Comment by PhilippS93** [comment]
Hi,

how can I use the getStrings extraction in the newest 8.0.0 version?

**Comment by C0deZLee** [comment]
We appreciate the updates and hard work on the library. However, post 7.0.0, since `GettextImporter` is gone, this library is unusable for us. The current documentation also isn't updated to reflect this change. Could we consider revising the functionality or updating the instructions?

**Comment by marcglasberg** [comment]
@bauerj Johann, do you think you can help with this, please? 

@PhilippS93 @C0deZLee This plugin was contributed by @bauerj . I don't know anything about it, and can't fix this myself. If Johann can't do it we need someone to contribute a PR to fix this. Please help if you can! Thanks.

**Comment by bauerj** [comment]
Hi,

sorry for my late reply. Looks like I missed the original thread.

Can you give more insight into the compatibility issues that arise from using the analyzer package?

If that's the only possibility we could move the *exporter* to a different package. However, IIRC the importers should not depend on the analyzer package.

Maintaining two different packages and keeping them in sync could create additional maintanance overhead so I'm not too happy about that 😕

**Comment by bauerj** [comment]
Thanks, I'm happy to hear that!

I still think it's crucial to understand the underlying issue first since it surely would apply to the split-off package as well.

**Comment by marcglasberg** [comment]
@bauerj I don't think the issue would apply to the split-off package:

1. There are projects that use `i18n_extension`, do NOT use getstrings, but do depend on specific versions of the analyzer that are incompatible with `getstrings`. These projects benefit on having `getstrings` as a separate project.
2. There are projects that use i18n_extension, use `getstrings`, and do NOT depend on the analyzer for anything else. These projects are indifferent from weather `getstrings` is a separate project or not.
3. There may exist projects that use both `i18n_extension` and `getstrings`, and do depend on specific versions of the analyzer that are incompatible with `getstrings`. I haven't found one of these projects yet, but they may exist. I have no idea if having `getstrings` as a separate project would benefit those projects or not, but probably yes? 

Also, regarding "keeping it on sync between versions" I don't think this will be a problem. It's unlikely that `i18n_extension` would change so much as to break `getstrings`. I actually think it would create less maintenance overhead: The GitHub issues would be separate, making it easier for you to get the necessary information. Also, I promise to be responsive when you need anything from me, and may keep the `getstrings` documentation in the `i18n_extension`, linking to your package. Having a separate project would give `getstrings` the recognition is deserves, and would make it easier for other people to contribute to it too, I believe.

**Comment by c0dezli** [comment]
We created a separate [i18n_extension_importer](https://pub.dev/packages/i18n_extension_importer) package so we are unblocked from this ongoing issue.


@bauerj Johann, please let us know if you’d like us to transfer the ownership of this package to you; we’d be more than happy to do so!

**Comment by marcglasberg** [comment]
@c0dezli Thank you so much for that! I should now update the documentation to point to your package.

**Comment by marcglasberg** [comment]
Hi @c0dezli I have just published `i18n_extension 10.0.0` pointing to your package, and updated the documentation:

_Note: Those importers were contributed by [Johann Bauer](https://github.com/bauerj), and were separated into their own package by [Xiang Li](https://github.com/c0dezli)._

One thing I noticed is that in https://pub.dev/packages/i18n_extension_importer you say:

> Note: Those importers were contributed by [Johann Bauer](https://github.com/bauerj). If you want to help creating importers for any of the other formats above, please PR here: https://github.com/marcglasberg/i18n_extension.

But now you should point to your new package instead. In other words, could you please fix this to say:

> Note: Those importers were contributed by [Johann Bauer](https://github.com/bauerj). If you want to help creating importers for any of the other formats above, please PR here: https://github.com/c0dezli/i18n_extension_importer.

Thank you!!
