### ISSUE TITLE
build fail with v8.0.0

### ISSUE THREAD

**Issue by edwin-alvarez** [marcglasberg/i18n_extension#127]
this method is breaking my build when using v8.0.0

  String modifier(Object identifier, String text) {
    return ((!startsWith(_splitter1)) ? _splitter1 : "") +
        "$this$_splitter1$identifier$_splitter2$text";
  }

xcode is marking $this

**Comment by marcglasberg** [comment]
That's very weird. I need more information. What's the error?

**Comment by henlamk** [comment]
Error: The getter 'this' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'this'.
            "$this$_splitter1$identifier$_splitter2$text";

**Comment by Sese-Schneider** [comment]
@marcglasberg I can confirm and reproduce this issue on ANDROID:
```
i18n_extension-8.0.0/lib/i18n_extension.dart:670:11: Error: The getter 'this' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'this'.
        "$this$_splitter1$identifier$_splitter2$text";
```

<details><summary>Flutter Version</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22621.1413], locale
    de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.3.6)
[!] Android Studio (version 2022.1)
    X Unable to find bundled Java version.
[√] IntelliJ IDEA Ultimate Edition (version 2022.3)
[√] Connected device (4 available)
[√] HTTP Host Availability
```
</details>

**Comment by Sese-Schneider** [comment]
Issue doesn't occur with the latest stable Flutter version `3.7.x`. 
@marcglasberg maybe you want to bump the minimum requirement for this package.
cc: @edwin-alvarez @henlamk

**Comment by marcglasberg** [comment]
Will do. Thanks.
