### ISSUE TITLE
Creating locale not changed globally

### ISSUE THREAD

**Issue by Kacpur** [marcglasberg/i18n_extension#13]
Hi, I started to use your plugin this week, so I'm still at discovery stage.

One of features I try to implement is having translations by language not key. And today after your update I tried to follow docs, specifically this one:
```
static var _t = Translations.byLocale("en", "US") +
    {
      "en_us": {
        "Hi.": "Hi.",
        "Goodbye.": "Goodbye.",
      },
      "es_es": {
        "Hi.": "Hola.",
        "Goodbye.": "Adiós.",
      }
    };
```

But in the plugin itself (1.3.0) I cannot create Locale by two Strings, it still require one combined String. It may be desired behaviour but still it's inconsistency between docs and actual code.

**Comment by marcglasberg** [comment]
I've fixed the docs. It must be `Translations.byLocale("en_us")`.
