### ISSUE TITLE
What happened to the JSONImporter?

### ISSUE THREAD

**Issue by DominikStarke** [marcglasberg/i18n_extension#132]
It seems to be gone but is still in the docs.

**Comment by PhilippS93** [comment]
seems related to https://github.com/marcglasberg/i18n_extension/issues/126

**Comment by WindyWin** [comment]
I met the same issue, the JSONImporter is on branche getStrings of this repo, but it didn't work.
So I fix it a little.

readLocalizationFile.dart
`import "dart:collection";
import "dart:convert";

import "package:flutter/cupertino.dart";
import "package:flutter/services.dart";

abstract class Importer {
  String get _extension;

  Map<String, String> _load(String source);

  Future<Map<String, Map<String, String>>> fromAssetFile(
      String language, String fileName) async {
    return {language: _load(await rootBundle.loadString(fileName))};
  }

  Future<Map<String, Map<String, String>>> fromAssetDirectory(
      String dir) async {
    var manifestContent = await rootBundle.loadString("AssetManifest.json");
    Map<String, dynamic> manifestMap = json.decode(manifestContent);

    Map<String, Map<String, String>> translations = HashMap();

    for (String path in manifestMap.keys) {
      if (!path.startsWith(dir)) continue;
      var fileName = path.split("/").last;
      if (!fileName.endsWith(_extension)) {
        debugPrint("➜ Ignoring file $path with unexpected file type "
            "(expected: $_extension).");
        continue;
      }
      var languageCode = fileName.split(".")[0];
      translations.addAll(await fromAssetFile(languageCode, path));
    }

    return convertMap(translations);
  }

// convert from {key1: valueInEn,...} + {key1:valueInVi,...} to {key1:{vi:valueInVi, en:valueInEn},...}
  Map<String, Map<String, String>> convertMap(
      Map<String, Map<String, dynamic>> map) {
    Map<String, Map<String, String>> result = {};

    List<String> languageKeys = map.keys.toList(); // ["vi", "en ", ...]
    Set<String> keywordKeys = {}; // {"Login": }
    // Get a union of all the keys from both objects
    for (var key in languageKeys) {
      keywordKeys = {...keywordKeys, ...map[key]!.keys};
    }

    // Loop through all the keys in the union
    for (String key in keywordKeys) {
      // Create a new object with the current key and its corresponding values, if both values are present
      if (languageKeys.every((element) => map[element]!.containsKey(key))) {
        // obj = {"en": "translate in English", "vi":"translate in Viet Nam"}}
        Map<String, String> obj =
            map.map((language, value) => MapEntry(language, value[key]));
        //
        result[key] = obj;
      }
    }

    return result;
  }

  Future<Map<String, Map<String, String>>> fromString(
      String language, String source) async {
    return {language: _load(source)};
  }
}

// /////////////////////////////////////////////////////////////////////////////

class JSONImporter extends Importer {
  @override
  String get _extension => ".json";

  @override
  Map<String, String> _load(String source) {
    return Map<String, String>.from(json.decode(source));
  }
}
`
on my translation file
`
import 'package:i18n_extension/i18n_extension.dart';
import './readLocalizationFile.dart';

extension Localization on String {
  static Translations _t = Translations("key");

  static Future init() async {
    Map<String, Map<String, String>> trans =
        await JSONImporter().fromAssetDirectory("assets/localization");
    _t = Translations.from("key", trans);
  }

  String get i18n => localize(this, _t);

  String fill(List<Object> params) => localizeFill(this, params);

  String plural(value) => localizePlural(value, this, _t);

  String version(Object modifier) => localizeVersion(modifier, this, _t);
}
`

**Comment by marcglasberg** [comment]
Yes, please see https://github.com/marcglasberg/i18n_extension/issues/126 and help fix this if you can. Thank you!

Meanwhile, the `JSONImporter` is in the `i18n_extension\test\getStrings` directory of this repo. I suggest you copy it from there, and run it.

**Comment by marcglasberg** [comment]
Find it in https://pub.dev/packages/i18n_extension_importer

**Comment by DominikStarke** [comment]
Thank you!
