### ISSUE TITLE
[v11.0.11] Method signature suggestion

### ISSUE THREAD

**Issue by SoftWyer** [marcglasberg/i18n_extension#137]
Having upgraded to the latest version from the previous one there was one breaking issue due to the changes in package structure and Type visibility.

In our code, using the old version, there was a reference to the type `TranslationsByLocale` but this is no longer visible.

However, both `TranslationsByLocale` and `TranslationsByText` are exposed by the following methods signatures:

```
static TranslationsByText byText(StringLocale defaultLocaleStr) => TranslationsByText...

static TranslationsByLocale byLocale(StringLocale defaultLocaleStr) => TranslationsByLocale...
```

Changing our code to use `Translation` solves our issue, but perhaps the signatures of the methods above could be changed to return `Translation` instead. Appreciate this would be a breaking change and may not be possible depending upon how they are used within the package.

**Comment by marcglasberg** [comment]
You are absolutely right. Actually, it was my intention to change the signatures, but the generics were so complex (as you can see if you look at the code) that by the time I made it work I forgot to change them.

I fixed the signatures, and also added this to the changelog:

```
* Translation subtype `TranslationsByLocale` still exist, but it's not visible anymore.
  If you were writing `TranslationsByLocale t = new TranslationsByLocale(...` you should now write
  `var t = Translations.byLocale(...`, or `Translations t = Translations.byLocale(...`
```

Keep in mind the recommended way is to simply use `var` or `final`: `var t = Translations.byLocale(...`

Thank you!
