### ISSUE TITLE
Problem with Flutter 3.22.0

### ISSUE THREAD

**Issue by marciorr** [marcglasberg/i18n_extension#138]
New version of Flutter (3.22.0) pinned intl to version 0.19.0
This is causing i18n_extension to show an error when we do "Pub get". It is important to update the intl in the i18n_extension's pubspec.yaml. I did this locally and it's working, but it would be great if this was updated in the next version. It's a simple update.
Best regards and great work with this dependency.

**Comment by marciorr** [comment]
Reference to this PR #139

**Comment by marcglasberg** [comment]
See version: 12.0.0
