### ISSUE TITLE
Country codes are 2 uppercase letters

### ISSUE THREAD

**Issue by hlemcke** [marcglasberg/i18n_extension#14]
Please write country codes in your examples as 2 uppercase letters according to IANA. See

https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

Scroll down to see the region codes.

**Comment by marcglasberg** [comment]
You are right of course, but unfortunately the `Locale` class doesn't force you to use the correct standards for country and language. You can basically type whatever you want. As a result it's very easy to make mistakes, and the most common one is not using uppercase letters. Try it:

```dart
test("Is Locale standardized? No it's not. That's why I normalize it as lowercase.", () {
    expect(Locale("pt", "br").toString(), "pt_br");
    expect(Locale("pt", "BR").toString(), "pt_BR");
    expect(Locale("pt", "BR"), Locale("pt", "BR"));
    expect(Locale("pt", "br"), isNot(Locale("pt", "BR")));
  });
```

To make it **case insensitive**, I'm normalizing it in lowercase. 

I suggest you open an issue to fix the `Locale` class itself. Once that's done I can follow the standard. If they don't fix the Locale class, in the future I'm going to study another possibility, which is for the `i18n_extension` to make sure the given  country and language are following the standard, and then point out the `Locale` is invalid.
