### ISSUE TITLE
With Flutter 3.22.0 the I18n() widget results in a blank screen on web and disables all gestures on other platforms (iOS, Android, etc.)

### ISSUE THREAD

**Issue by ronjb** [marcglasberg/i18n_extension#140]
Using the example1 app in this package, running on web, just a blank screen shows. Running on another platform, e.g. iOS, the UI shows but no taps work. If I remove the I18n widget from the tree, taps work, and the web version is no longer blank.

**Comment by marciorr** [comment]
I'm having the same problem. Strangely if we use the old version 11.0.12 and simply change the intl to 0.19.0 version on the i18n_extension, everything works correctly.

**Comment by marciorr** [comment]
I found the problem. It's in the i18n_widget.dart file. This particular code is causing this problem, it didn't exist in the previous version:

`WidgetsBinding.instance.addPostFrameCallback((_) {
      WidgetsBinding.instance.reassembleApplication();
    });`

![2024-05-14_13h58_13](https://github.com/marcglasberg/i18n_extension/assets/22574940/2bb40f9d-558b-4563-bc2a-a8f662c5b4d9)

If we remove this code it works perfectly. This code was added in the April 1, 2024 commit (d7dab48).

Maybe @marcglasberg can check it out.

**Comment by marciorr** [comment]
This is what Gemini told me about this code:

Intended Purpose (Incorrect):

The code might have been written with the intention of forcing the app to redraw or update itself after some event. However, this approach has a significant flaw.

Reason for Freezing:

Reassembling the entire application repeatedly within a single frame is a very expensive operation. It involves tearing down the existing widget tree, rebuilding it from scratch, and then redrawing the UI. Doing this constantly after every frame will overwhelm the Flutter engine and lead to a frozen app.

**Comment by marciorr** [comment]
I just opened a PR with the fix. Let's hope it is approved quickly. #141

**Comment by marcglasberg** [comment]
Published version: `12.0.1`

**Comment by marcglasberg** [comment]
Just tested it works when removing this.

> Reassembling the entire application repeatedly within a single frame is a very expensive operation. It involves tearing down the existing widget tree, rebuilding it from scratch, and then redrawing the UI. Doing this constantly after every frame will overwhelm the Flutter engine and lead to a frozen app.

Yes, it was expensive, but you don't change languages all the time, so this was not a problem. But it seems there are other incompatibilities. Thanks @ronjb for finding this so quickly and thanks @marciorr for the PR.
