### ISSUE TITLE
Initial system locale is not loading

### ISSUE THREAD

**Issue by Kacpur** [marcglasberg/i18n_extension#15]
Hi, I try to fetch system locale to show content in the language of the device system but the locale that is set by default is always null which results in displaying the first language.
I have the exact same result in your example app. In your example app you support two languages: English US and Portuguese Brazil. But when I open the app, it always show content in English, even if I set device language to the second one.

EDIT: Ok, I took wrong locale to check, systemLocale is showing default locale (en_US). Yet still, the content is shown in default language instead of device locale.

**Comment by Kacpur** [comment]
Ok, I resolved this by adding `localeResolutionCallback`, `localizationsDelegates` and `supportedLocales` to the MaterialApp constructor.  Closing.

**Comment by marcglasberg** [comment]
Added this info to the docs: version: 1.3.2.
