### ISSUE TITLE
Newbie info for readme

### ISSUE THREAD

**Issue by GOTFire** [marcglasberg/i18n_extension#17]
Hello,

I just want add i18n support to my app.I just find your awesome extension.I followed tutorial but its not worked(Its not change lang) so i just searched for my mistakes.Followed official flutter i18n tutorial and checked this extension issues.I found my problem.I need add these to MaterialApp

https://flutter.dev/docs/development/accessibility-and-localization/internationalization

```
MaterialApp(
          localizationsDelegates: [
            // ... app-specific localization delegate[s] here
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          supportedLocales: [
            const Locale('en', "US"), // En
            const Locale('tr', "TR"), // TR
          ],
          ...
          ),
          home: I18n(child: screen()))
```

So its my first time on i18n and i dont know to do this.If you add this to readme file i think its will be helpfull for others

**Comment by marcglasberg** [comment]
Added this info to the docs: version: 1.3.2.
