### ISSUE TITLE
Feature Request: Integration with Flutter Localizations

### ISSUE THREAD

**Issue by hlemcke** [marcglasberg/i18n_extension#19]
Flutter localizations are still required to translated Flutter widgets. It would be great to have this integration realized within i18n.

Please have a look at the example app from https://github.com/djarjo/flutter_input 

I was able to combine changing both localizations with `InputLanguage`.
But it required to have _I18n_ as topmost widget and even one more instance variable of `Locale`. Maybe there is a much more elegant solution by providing something like `I18n.locale` to `MatterialApp `even if `I18n `is a child of `MaterialApp`?

**Comment by marcglasberg** [comment]
I'm not sure I understand what you want to do, sorry. Could you be more clear, and maybe provide code examples here?

**Comment by marcglasberg** [comment]
I will close this, since you did not reply so far, and I can't understand what you want. Please feel free to reopen it if you have more info to help me. Thanks.
