### ISSUE TITLE
Translation file produces pub.dev issue when uploading

### ISSUE THREAD

**Issue by hlemcke** [marcglasberg/i18n_extension#20]
Each translation file like `flutter_input/lib/src/country.i18n.dart` from https://github.com/djarjo/flutter_input

> extension Localization on String {
>   String get i18n => localize(this, _t);
>   static final _t = Translations('en') +
>     {
>       'en': 'Australia',
>       'de': 'Australien',
>     } +
> 

produces a _pub.dev_ issue when uploading a package:

> Local variable _t not used.

I modified the file to have `_t` as a class local variable but that seems a bit strange.

**Comment by marcglasberg** [comment]
That variable is actually being used, so it's a a pub.dev bug. I've seen the same problem in some other packages of mine. I suggest you fill an issue to pub.dev.
