### ISSUE TITLE
Detect missing translations or keys without running the code

### ISSUE THREAD

**Issue by svendroid** [marcglasberg/i18n_extension#23]
Is there a way to detect missing translations without running the code? 
e.g. in my app I am not testing every Snackbar, Dialog or smaller UI Widget, therefore those string do not show up when using `expect(Translations.missingKeys, isEmpty); expect(Translations.missingTranslations, isEmpty);` in a test. 

I am thinking about something like a additional rule for the dart analyzer, which seems not possible at the moment as mentioned here https://github.com/dart-lang/linter/issues/697. An alternative for static analysis is mentioned here: https://github.com/dart-lang/linter/issues/697#issuecomment-569080238

Or is there a different way one could achieve this functionality?

**Comment by marcglasberg** [comment]
Apart from those you mentioned, a separate IntelliJ plugin, or a build_runner, could use the Dart AST to check all uses of translation. It would be great if someone could create one of those tools, but I won't make one myself.

I have another suggestion, which is to log all missing keys in production. Even if your tests won't cover everything, your users will, during normal use. Likely you will find all missing keys very fast.
