### ISSUE TITLE
Logic of missing translations

### ISSUE THREAD

**Issue by crizant** [marcglasberg/i18n_extension#26]
When using `Translations.byLocale`, we should not need to provide the translations of the default locale like:

```
var t = Translations.byLocale("en_US") +
        {
          "en_us": {
            "Hi.": "Hi.",
            "Goodbye.": "Goodbye.",
          },
        };
```

This is boilerplate.

But if we don't provide it, an error is shown: `➜ There are no translations in 'en_US' for "Hi".`
This behavior should be fixed.

I have created #25 to fix this issue, please take a look of it. Thanks.

**Comment by marcglasberg** [comment]
This already works. The docs say: "Note above, since "en_us" is the default locale you don't need to provide translations for those".

But it was recording it as a missing translation. It should not. Good catch!

I've added tests, and I'm bumping the package version to 1.3.4. Thanks.
