### ISSUE TITLE
_systemLocale null

### ISSUE THREAD

**Issue by JCKodel** [marcglasberg/i18n_extension#3]
![image](https://user-images.githubusercontent.com/379339/69474355-f1be5d00-0d9e-11ea-85fd-deea472497c1.png)

```
I/flutter (14367): [2019-11-23 04:10:51.568618 | ConsoleHandler | INFO] NoSuchMethodError: The method 'replaceAll' was called on null.
I/flutter (14367): Receiver: null
I/flutter (14367): Tried calling: replaceAll(RegExp: pattern=^[_ ]+|[_ ]+$ flags=, "")
I/flutter (14367): [2019-11-23 04:10:51.574261 | ConsoleHandler | INFO]
I/flutter (14367): [2019-11-23 04:10:51.576518 | ConsoleHandler | INFO] ------- STACK TRACE -------
I/flutter (14367): [2019-11-23 04:10:51.598902 | ConsoleHandler | INFO] #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
I/flutter (14367): [2019-11-23 04:10:51.602977 | ConsoleHandler | INFO] #1      I18n._trimLocale 
package:i18n_extension/i18n_widget.dart:53
I/flutter (14367): [2019-11-23 04:10:51.603718 | ConsoleHandler | INFO] #2      I18n.localeStr 
package:i18n_extension/i18n_widget.dart:48
I/flutter (14367): [2019-11-23 04:10:51.604203 | ConsoleHandler | INFO] #3      _effectiveLocale 
package:i18n_extension/i18n_extension.dart:213
I/flutter (14367): [2019-11-23 04:10:51.604531 | ConsoleHandler | INFO] #4      localize 
package:i18n_extension/i18n_extension.dart:48
I/flutter (14367): [2019-11-23 04:10:51.604829 | ConsoleHandler | INFO] #5      Localization.i18n 
```

**Comment by marcglasberg** [comment]
The above info is not enough info for me to see what's going on. It just tells me the locale is null. Please, provide me with a single file with a minimum runnable example, including the main method.

However, I would guess, since the locale is unknown, that you forgot to wrap your widgets with I18n(child: ...). Please make sure you are doing this:

    @override
    Widget build(BuildContext context) {
     return MaterialApp(
       home: I18n(child: ...)
     );
    }

**Comment by weraaaaz** [comment]
I have the same error. Using`Text("Hello there".i18n)` and `my_widget.i18n.dart` file

**Comment by weraaaaz** [comment]
Ok, fixed by adding ```@override
Widget build(BuildContext context) {
 return MaterialApp(
   home: I18n(child: ...)
 );
}``` . It wasn't very clear in docs that you need this if you use translatable strings

**Comment by marcglasberg** [comment]
@weraaaaz I'll make it clearer in the docs.
