### ISSUE TITLE
Howto: missingKeyCallback

### ISSUE THREAD

**Issue by edwin-alvarez** [marcglasberg/i18n_extension#33]
can you provide more details about how to use this? or upload an example to your example proyect.

Translations.missingKeyCallback = (key, locale)
  => throw TranslationsException("Translation key in '$locale' is missing: '$key'.");

Translations.missingTranslationCallback = (key, locale)
  => throw TranslationsException("There are no translations in '$locale' for '$key'.");

**Comment by marcglasberg** [comment]
You may set up callbacks that the `i18n_extension` package will call whenever it detects a missing translation. You can then program these callbacks to throw errors if any translations are missing,
or log the problem, or send emails to the person responsible for the translations.

How to use this? Just write this in your app's initialization code:

    Translations.missingKeyCallback = (key, locale) { [write some function that uses the missing key and locale here] }

    Translations.missingTranslationCallback = (key, locale) { [write some function that uses the missing key and locale here] }

**Comment by ManojMMWWIndia** [comment]
where do I add this? can you please update sample app to show how to disable this? 
I have settings page from where I change locale, It used to work perfectly before new flutter and this package update, Not when I try to translate it some times works sometimes not. I have to go back and forth on that page to get translations working.

**Comment by marcglasberg** [comment]
@ManojMMWWIndia That's kind of serious. I haven't had other reports about anything changing with Flutter 1.17. Could you please create an example that demonstrate the problems you are having?

**Comment by edwin-alvarez** [comment]
I'm using 1.18.0 without issues

![image](https://user-images.githubusercontent.com/5774873/82929176-1951d600-9f38-11ea-9ba3-ab2e7d3e491f.png)
