### ISSUE TITLE
Import and Export to .po

### ISSUE THREAD

**Issue by bitsmakerde** [marcglasberg/i18n_extension#34]
Hello,

I see in the documentary that there is an export and an import for po. Unfortunately I don't understand how I can use it.

Are the commands for the shell?

Thanks

**Comment by marcglasberg** [comment]
Actually there is no export/import. What I say in the docs is that since the package uses regular Dart maps to keep the translations, it would, in principle, be very easy to import from any format. You just need to read the .po file and create a regular map in memory.
