### ISSUE TITLE
Set locale without context

### ISSUE THREAD

**Issue by jasonlaw** [marcglasberg/i18n_extension#35]
Hi,

I need this to work with flutter localization.
I have a custom AppLocalizations, when ever there is locale changed, I want to propagate the changes to i18n too, without the context.

Btw, could you provide a example or sample code how to have this work with flutter localization.

Thanks in advance.

**Comment by jasonlaw** [comment]
Looks like I don't even need the custom AppLocalizations at all, am I right?

**Comment by marcglasberg** [comment]
You are right.
