### ISSUE TITLE
issue with plurals

### ISSUE THREAD

**Issue by edwin-alvarez** [marcglasberg/i18n_extension#38]
looks like plural is not working

Text('0 Selected'.i18n.plural(_itemsSelected.length)),

      {
        "en": "0 Selected"
        .zero("0 Selected")
        .one("1 Selected")
        .two("2 Selected")
        .many("%d Selected"),
        "es": "0 Seleccionado"
        .zero("0 Seleccionados")
        .one("1 Seleccionado")
        .two("2 Seleccionados")
        .many("%d Seleccionados"),
      } 

The following TranslationsException object was thrown building ViewBookNotesScreen(dirty, dependencies: [MediaQuery], state: _ViewBookNotesScreenState#c9334):
  Translation key in 'en' is missing: '￿0 Selected￿0￾0 Selected￿1￾1 Selected￿2￾2 Selected￿M￾%d Selected'.

**Comment by marcglasberg** [comment]
This is wrong:

    Text('0 Selected'.i18n.plural(_itemsSelected.length)),

You should do:

    Text('0 Selected'.plural(_itemsSelected.length)),

**Comment by edwin-alvarez** [comment]
thanks @marcglasbergs
