### ISSUE TITLE
Allow to export translation templates

### ISSUE THREAD

**Issue by bauerj** [marcglasberg/i18n_extension#39]
Having worked with gettext before, the approach used in your project is very familiar in that source strings are used as identifiers.

[xgettext](https://linux.die.net/man/1/xgettext) is a tool that automatically generates the '.po' files which can then be sent to translators (or online services). As far as I understand, your project does not contain such a tool yet. Would you think it might be a good idea to add a small Dart utility for that purpose to your project?

It might be sufficient to run a regular expression against project files (at least for most cases). But maybe I am overlooking something there. If you feel this could benefit your project I might work on a pull request.

**Comment by marcglasberg** [comment]
That's very interesting, I didn't know about gettext. Indeed it's a similar approach.

Yes, the project would benefit from such a tool, but it's not necessary to run a regular expression. There's a much easier way to do it. The package will automatically list all keys into a map if you use some unknown locale. For example, create a Greek locale if your app doesn't have Greek translations. Then you can run the app and manually or automatically go through all the screens. It will then list all keys into `Translations.missingTranslationCallback`.

Then you can read from this map and create the `.po` file.

**Comment by bauerj** [comment]
I see, that would certainly work more reliably. However, I think it would be very hard to go through all screens (and dialogs) with different settings without writing code specifically for each individual project.

My goal is to have something that runs as part of the CI pipeline after each commit and uploads the new strings to a service like crowdin.

**Comment by marcglasberg** [comment]
There is this package that goes through all screens automatically: https://pub.dev/packages/flutter_storyboard

However, if you feel a regular expression is better, go for it. I'll accept the pull request.

**Comment by marcglasberg** [comment]
@bauerj Hey, your tests are not compiling. The `GetI18nStrings()` constructor needs a `sourceDir` parameter. Could you please fix this and PR again?

**Comment by bauerj** [comment]
Whoops, sorry! That was a last minute change and I forgot to change the tests accordingly. I opened a new PR that fixes this.
