### ISSUE TITLE
How to translate interploated String to all languages

### ISSUE THREAD

**Issue by learnpainless** [marcglasberg/i18n_extension#4]
i want to translate interploated String,

for example:
"Harry like %s"

**Comment by marcglasberg** [comment]
Just published version 1.1.2 to do what you want:

### Interpolation

You can use the `fill` method to do interpolations: 

```dart   
static var t = Translations("en_us") +
  {
    "en_us": "Hello %s, this is %s",
    "pt_br": "Olá %s, aqui é %s",
  };
  
...
                                               
print("Hello %s, this is %s".i18n.fill(["John", "Mary"])); 
```

The above code will print `Hello John, this is Mary` if the locale is English,
or `Olá John, aqui é Mary` if it's Portuguese.

It uses the <a href="https://pub.dev/packages/sprintf">sprintf</a> package internally.
I don't know how closely it follows the C sprintf specification, 
but <a href="https://www.tutorialspoint.com/c_standard_library/c_function_sprintf.htm">here it is</a>.
