### ISSUE TITLE
[Web] InheritedI18n is not supported

### ISSUE THREAD

**Issue by DenisBarzanov** [marcglasberg/i18n_extension#43]
When I ran my Flutter app on the Web I ran across this issue:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
js_primitives.dart:30 The following UnsupportedError was thrown building _InheritedI18n:
Unsupported operation: Platform._operatingSystem
The relevant error-causing widget was:
_InheritedI18n
file:///home/dennis/.pub-cache/hosted/pub.dartlang.org/i18n_extension-1.4.0/lib/i18n_widget.dart:154:12
```

This is strange because it has nothing to do with native functionality and, besides, it is listed as supported on [pub.dev](https://pub.dev/packages/i18n_extension)

**Comment by marcglasberg** [comment]
Yes, I have no idea what is going on here. I haven't actually had that much experience in Flutter web so far. Maybe someone else can help with ideas.

**Comment by marcglasberg** [comment]
@DenisBarzanov Hey Denis, does this problem still exist with the most recent Flutter version and the most recent i18n_extension?
