### ISSUE TITLE
.i18n.fill doesnt generate string with flutter pub run i18n_extension:getstrings

### ISSUE THREAD

**Issue by Freundschaft** [marcglasberg/i18n_extension#44]
When I run flutter pub run i18n_extension:getstrings all strings get exported, apart from interpolated strings that I generate with .i18n.fill
Is that a bug in the getstrings generator?

It seems that the generator ignores strings that have a linebreak before .i18n or .fill.

so if I have

```
'mysamplestring %s'
.i18n
.fill(test)
```

it doesnt detect the string during generation

but

`'mysamplestring %s'.i18n.fill(test)`

works

I assume this is a bug in how getStrings detects strings in code files

**Comment by marcglasberg** [comment]
The getstrings utility was contributed by Johann Bauer. I don't actually use it, so you have to post this question to him: @bauerj

**Comment by bauerj** [comment]
Yes, that is a bug. I will take a look at this later.

**Comment by bauerj** [comment]
Thanks @Freundschaft, this is fixed now in #45. 

Just out of curiosity: How does your workflow look like? Do you manually translate by editing the JSON file?

**Comment by Freundschaft** [comment]
perfect, thanks.
We don't have a workflow set up yet, I am generating the JSON files, and so far our current plan is to translate the strings in the JSON file manually, yes.

**Comment by marcglasberg** [comment]
@Freundschaft Please test verion [1.4.1].

**Comment by Freundschaft** [comment]
works, thank you!

**Comment by bauerj** [comment]
Do you also use i18n.fill?
