### ISSUE TITLE
Where to correctly place `I18n` in wiget tree?

### ISSUE THREAD

**Issue by hlemcke** [marcglasberg/i18n_extension#50]
Hi,

the readme says, I should put `I18n` for parameter home below MaterialApp. But when I provide routes to MaterialApp then I cannot use home, because I have one route named '/'. Where should I put `I18n` correctly?

**Comment by marcglasberg** [comment]
Please, see this discussion: https://github.com/marcglasberg/i18n_extension/issues/10
