### ISSUE TITLE
How to extract string from array of strings during code generation export

### ISSUE THREAD

**Issue by fonkamloic** [marcglasberg/i18n_extension#51]
I am using `flutter pub run i18n_extension:getstrings` to extract my string. 
How to a extract from an array.

**Comment by marcglasberg** [comment]
The getstrings utility was contributed by Johann Bauer ( @bauerj ) so I hope he can answer your question.

**Comment by bauerj** [comment]
Hey @fonkamloic,

I would assume something like this would work:

    var test = ["this".i18n, "should".i18n, "work".i18n];

Are you trying to do something else?

**Comment by fonkamloic** [comment]
Hello @bauerj  and @marcglasberg, thank you for your replies.

I did just that and it works. Thanks.
