### ISSUE TITLE
Loading from JSON file will be async/await and cannot be applied with extension

### ISSUE THREAD

**Issue by seonar22** [marcglasberg/i18n_extension#52]
Reading from JSON file will be Future value and cannot be applied to used as in example.

```
  static var _t = Translations("en_us") + JsonReader.loadFromAsset();

```

**Comment by EArminjon** [comment]
up

**Comment by EArminjon** [comment]
@seonar22 Maybe something like that : https://github.com/marcglasberg/i18n_extension/issues/53

**Comment by marcglasberg** [comment]
@seonar22 You cannot declare a variable and then use async code like this. But you can load its contents in the apps initialization:

```dart
static Translations _t;

void setTranslations(Translations t) => _t = t;

// In the app's initialization.
init() async {
setTranslations(Translations("en_us") + await JsonReader.loadFromAsset());
}
```
