### ISSUE TITLE
i18n.fill() does not work

### ISSUE THREAD

**Issue by HenrikThien** [marcglasberg/i18n_extension#6]
The method isn't found when I try to do this:

`Text("hello %s".i18n.fill(["Test"]));`

I goes the method to overwrite it in the extension is missing?
Something like 
`String get i18n => localize(this, _t);
  String plural(int value) => localizePlural(value, this, _t);`

**Comment by HenrikThien** [comment]
Okay I've solved the issue by using this way in my extension file:
`String add(List<Object> params) => localize(this, _t).fill(params);`

But thats not the way as described as in the documentation

**Comment by marcglasberg** [comment]
@HenrikThien 

Please upgrade to version 1.2.0.

Your translations file may declare a `fill` method to do interpolations:

```dart   
static var _t = Translations("en_us") +
  {
    "en_us": "Hello %s, this is %s",
    "pt_br": "Olá %s, aqui é %s",
  };
   
String get i18n => localize(this, t);
   
String fill(List<Object> params) => localizeFill(this, params);       
```

Then it will work as expected.

**Comment by darthdie** [comment]
If it requires manually adding the method, then this should be noted in the documentation. As it stands it sounds like a built-in function along with `plural`.

**Comment by marcglasberg** [comment]
@darthdie 

Both `plural()` and `fill()` are build-in. And both of them must be added to the translations file. This file is created by the developer, and is the only one imported into the widget file, so there's no way around it.

However, you are right that I should have added `fill()` to `default.i18n.dart`, which is to be used temporarily while the translations file is not created. This is now done in version 1.3.5.

**Comment by darthdie** [comment]
Appreciate it! It just threw me off when I read at the beginning of the docs
> Also, interpolating strings is easy, with the fill method:

And then when I went to use it the method was unable to be found 😅

**Comment by Bernardo-Junior** [comment]
### I use my fill this way:

`  String fill(List<Object> params) {
    String result = this;
    for (final param in params) {
      if (param is Map<String, dynamic>) {
        param.forEach((key, value) {
          result = result.replaceAll('#{$key}', value.toString());
        });
      }
    }
    return result;
  }`,

And I create a variable called i18nInterpolate to use only texts that have variables: 

`  static final _tInterpolate = Translations.byLocale('pt_br') +
      {
        'pt_BR': {
          'Texto exemplo #{variable} correta':
              'Texto exemplo #{variable} correta'
        },
      }`,

`  String get i18nInterpolate => localize(this, _tInterpolate);`

This way I can use the text itself as a translation key: 

`Text( 'Texto exemplo #{variable} correta'.i18nInterpolate.fill([ {'variable': 1}],), )`
