### ISSUE TITLE
Plurals: accept empty string for zero()

### ISSUE THREAD

**Issue by vnz1** [marcglasberg/i18n_extension#61]
Currently for the following code:

```json
"en_us": "abc".zero("").many("abc"),
"hu_hu": "abc".zero("").many("abc"),
```

I got an exception: `Invalid text version for '0￾' (key: 'abc', locale: 'hu_hu')`. But I would like to get an empty string.
(version: 1.4.6)

**Comment by marcglasberg** [comment]
Fixed in version 2.0.0.
