### ISSUE TITLE
Plurals: i18n gives garbage string for missing plurals

### ISSUE THREAD

**Issue by vnz1** [marcglasberg/i18n_extension#62]
In case of the following code:

```json
"en_us": "%d abc".zero("%d abc").one("%d abc").many("%d abcs"),
"hu_hu": "%d abc".zero("%d abc").many("%d abc"),
```

I got garbage string when 1. But I would like to get the value of the "many" in this case because some languages spelling of singular and plural forms are same.
(version: 1.4.6)

**Comment by marcglasberg** [comment]
Version 2.0.0 has a fix for this. It will use the unversioned string, not "garbage":

```
"hu_hu": "unversioned".zero("zero").many("many"),
```

Also note the new plural modifiers: `zeroOne` (for 0 or 1 elements), and `oneOrMore` (for 1 and more elements).
