### ISSUE TITLE
Import .po test not passing.

### ISSUE THREAD

**Issue by marcglasberg** [marcglasberg/i18n_extension#65]
@bauerj 

I am getting a `FormatException` when running your `test/import_test.dart` test.

```
package:gettext_parser/src/po/parser.dart 117:5   Node.parse
dart:_internal                                    ListIterable.fold
package:gettext_parser/src/po/parser.dart 7:52    PoParser.parse
package:gettext_parser/gettext_parser.dart 52:19  _Po.parse
package:i18n_extension/io/import.dart 60:41       GettextImporter._load
package:i18n_extension/io/import.dart 41:23       Importer.fromString
test\import_test.dart 18:47                       main.<fn>

FormatException
```

**Comment by bauerj** [comment]
Thanks for letting me know. Apparently my git installation has "helpfully" converted the newlines in the .PO file to Windows format. The upstream parser is not able to handle that. I created a PR (https://github.com/cah4a/dart_gettext_parser/pull/3) with a simple fix there.

A workaround for the test would be to convert the file back to Unix newlines.
