### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by nerder** [marcglasberg/i18n_extension#68]
This extension need to be migrated to null safety

**Comment by marcglasberg** [comment]
Will do that as soon as it goes to stable, unless someone contributes a PR to that end. I heard nnbd arrives March 3rd.

**Comment by nerder** [comment]
For the recommended approach for packages  is to migrate now that NNBD is in `beta`, and for apps when in `stable`, but only after the dependency of this packaged are migrated also as it's explained here: https://dart.dev/null-safety/migration-guide#step1-wait

Anyway I open the issue since I'll probably take the migration myself :)

**Comment by marcglasberg** [comment]
Yes, I know the recommended approach. If you can contribute the migration it will be much appreciated, thanks!

**Comment by IchordeDionysos** [comment]
The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

Probably blocked by cah4a/dart_gettext_parser#4

**Comment by IchordeDionysos** [comment]
The new Dart version with null-safety was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by marcglasberg** [comment]
Yes, that's the last of my 13 packages that I need to migrate. I'll try to do it during this weekend.

**Comment by cah4a** [comment]
Hi guys!

I'm a maintainer of [dart_gettext_parser](https://github.com/cah4a/dart_gettext_parser)
Happy to inform you that I've just published a null-safe version of the package.

**Comment by marcglasberg** [comment]
See version 3.0.0.

**Comment by IchordeDionysos** [comment]
@marcglasberg thank you very much 😍  This is really helpful 👍
