### ISSUE TITLE
error: This requires the 'extension-methods' experiment to be enabled

### ISSUE THREAD

**Issue by edin45** [marcglasberg/i18n_extension#7]
I copyed the example code: 

`import 'package:i18n_extension/i18n_extension.dart';

extension Localization on String {

  static var _t = Translations("en_us") +
    {
      "en_us": "Hello, how are you?",
      "pt_br": "Olá, como vai você?",
      "es": "¿Hola! Cómo estás?",
      "fr": "Salut, comment ca va?",
      "de": "Hallo, wie geht es dir?",
    };

  String get i18n => localize(this, _t);
}`

but I get this error: 

![Error](https://user-images.githubusercontent.com/48309852/72258445-65961c80-360e-11ea-8b04-8d974689d354.png)

how can i fix this bug?

**Comment by HenrikThien** [comment]
You need to enable Dart >= 2.6 to use extensions. Change your pubspec.yaml file to something like this:
`sdk: ">=2.6.0 <3.0.0"`

**Comment by edin45** [comment]
Thanks it worked for me
