### ISSUE TITLE
Cannot import "real" .po files

### ISSUE THREAD

**Issue by tiloc** [marcglasberg/i18n_extension#70]
PO files typically start with a section:
msgid ""
msgstr "Lots of header information"

This results in an empty key at the very beginning of the every file.

The add code throws an exception when that happens, because the "key.isEmpty" is triggering.
Suggestion: When an add for an empty key is attempted just return without doing anything.

```
void add({
    @required String locale,
    @required String key,
    @required String translatedString,
  }) {
    if (locale == null || locale.isEmpty) throw TranslationsException("Missing locale.");
    if (key == null || key.isEmpty) throw TranslationsException("Missing key.");
    if (translatedString == null || translatedString.isEmpty)
      throw TranslationsException("Missing translatedString.");
    // ---
```

**Comment by tiloc** [comment]
@marcglasberg Unfortunately, the changes which have been made to my PR before merging will continue to break this scenario.
In the .po scenario, the key is empty and the translatedString is not empty. This needs to be silently tolerated. My PR did that. With the changes to the PR it will continue to throw exceptions.

**Comment by marcglasberg** [comment]
To be frank, I believe this should have been dealt with by the PO importer. I accepted this as an easy fix, however, it will return only if both the `key` and the `translatedString` are empty. The reason is that if the `translatedString` this points to an error which will be silently ignored.

Please help me understand this. In the "real" po, what is the `translatedString` when the `key` is `null`?

**Comment by tiloc** [comment]
In "real" PO, there is never a key which is null. That's why I continued to throw in that case.
But there is by convention an empty key at the beginning of every file and the translatedString for that key is all the header information of the .po file. That's why I made the code tolerant for that scenario.

**Comment by tiloc** [comment]
But where does the PO importer live? I kind of agree with your point that the specialties of certain file formats should be placed in the importers for these formats.

**Comment by marcglasberg** [comment]
The importer was contributed by <a href="https://github.com/bauerj">Johann Bauer</a>.

**Comment by tiloc** [comment]
Then I guess my need would better be located maybe here: https://github.com/marcglasberg/i18n_extension/blob/0b574263c3c776aa3880af9823416c61b26731b0/lib/io/import.dart#L64

Please feel free to rollback the PR. Right now it complicates the code but will still not allow the import of PO files.

**Comment by marcglasberg** [comment]
I'll change this:

```
class GettextImporter extends Importer {
  @override
  String get _extension => ".po";

  @override
  Map<String, String> _load(String source) {
    Map<String, String> out = {};
    Map translations = gettext_parser.po.parse(source)["translations"][""];
    for (Map translation in translations.values) {
      if (translation.isNotEmpty) {
        String msgstr = translation["msgstr"][0];
        if (msgstr != "") {
          String msgId = translation["msgid"];
          if (msgId != "") out[msgId] = msgstr;
        }
      }
    }
    return out;
  }
}
```

Into this:

```
class GettextImporter extends Importer {
  @override
  String get _extension => ".po";

  @override
  Map<String, String> _load(String source) {
    Map<String, String> out = {};
    Map translations = gettext_parser.po.parse(source)["translations"][""];
    for (Map translation in translations.values) {
      if (translation.isNotEmpty) {
        String msgstr = translation["msgstr"][0];
        if (msgstr != "") {
          String msgId = translation["msgid"];
          if (msgId != "") out[msgId] = msgstr;
        }
      }
    }
    return out;
  }
}
```

This will remove the empty keys in the importer.

**Comment by marcglasberg** [comment]
@tiloc Could you please test version [3.0.1] already published to pub.dev, and tell me if it now works?

**Comment by marcglasberg** [comment]
@bauerj Hope you don't mind, I did some adjustments to your importer.

**Comment by bauerj** [comment]
Sure, thanks! The files I use don't have a header so I didn't spot this issue but I agree this would be a very common problem.

**Comment by tiloc** [comment]
@marcglasberg I updated to 3.0.3 and it works great! Thank you! And also the null-safety is much appreciated!
