### ISSUE TITLE
pub run i18n_extension:getstrings  malfunctions if you have comments with single apostrophes (eg don't, it's, 10's)

### ISSUE THREAD

**Issue by fne00** [marcglasberg/i18n_extension#72]
The getstrings function seems operate by finding an opening single or double quote, and then looking for the end of the string ... then it looks to see it .i18n (etc) is applied.

This goes wrong if you have unbalanced ' or " characters in the dart file.
This can easily happen if you have comment lines with words like: don't, can't, isn't, it's .

**Comment by marcglasberg** [comment]
The `getstrings` utility was contributed by @bauerj 

Hopefully he can answer you. Thanks.

**Comment by bauerj** [comment]
@fne00 Can you provide some Dart code that triggers this issue?

**Comment by fne00** [comment]
@bauerj  Take a Dart App/File that is working and add a comment like this to the code:

`// You will find it doesn't work past this point`

**Comment by bauerj** [comment]
Indeed, I can confirm your issue. I will push a fix on Monday.

**Comment by bauerj** [comment]
Hey @fne00,

I improved the utility to fix this. Me not catching this error probably means I should write more comments in my code 🤔

**Comment by fne00** [comment]
@bauerj  Thanks - That's great.
