### ISSUE TITLE
How to import PO files from assets

### ISSUE THREAD

**Issue by ahmedalrifai** [marcglasberg/i18n_extension#74]
Hello all 

i am trying load translation from po files, i found this code in the docs 

```
import 'package:i18n_extension/io/import.dart';
import 'package:i18n_extension/i18n_extension.dart';

void loadTranslations() async {
  TranslationsByLocale translations =
    Translations.byLocale("en_GB")
    + await GettextImporter().fromAssetDirectory("assets/locales");
}
```

But i don't know where to put it and how to use it can someone give me an example to import PO files.

sorry if my question is obvious to you i cant find an answer to this 😁

**Comment by marcglasberg** [comment]
The importer was contributed by Johann Bauer @bauerj.

Maybe he can help you.

**Comment by ahmedalrifai** [comment]
Thanks but i found where to put this code.

**Comment by bauerj** [comment]
For reference: [this](https://github.com/marcglasberg/i18n_extension/issues/63#issuecomment-770056237) is what I would recommend.

**Comment by ahmedalrifai** [comment]
I will use the recommend way then. Thanks alot
