### ISSUE TITLE
Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null. Try calling using ?. instead.

### ISSUE THREAD

**Issue by Aashique** [marcglasberg/i18n_extension#75]
packages/flutter_localizations/lib/src/material_localizations.dart:413:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
Try calling using ?. instead.
    ).replaceFirst(r'$selectedRowCount', formatDecimal(selectedRowCount));
      ^^^^^^^^^^^^

**Comment by marcglasberg** [comment]
This is a problem in flutter_localizations, not in i18n_extension. I think you filled this issue in the wrong package.
