### ISSUE TITLE
Package has "uses-material-design: true"?

### ISSUE THREAD

**Issue by HarukaMa** [marcglasberg/i18n_extension#77]
Does this package really need material icons? It's quite possible that apps using this package does not need material icons and have the settings on `false`, but flutter complains:

> package:i18n_extension has `uses-material-design: true` set but the primary pubspec contains `uses-material-design: false`. If the application needs material icons, then `uses-material-design`  must be set to true.

It seems this does not actually affect anything, but I think if this package does not need it, it'd be better to leave it off.

**Comment by marcglasberg** [comment]
Will remove it.
