### ISSUE TITLE
Merge POT plurals fix

### ISSUE THREAD

**Issue by iuriegutu95** [marcglasberg/i18n_extension#79]
Hey @marcglasberg , there is an open pull request from me that allows plurals (in the simplest form) to work on POT files. can you merge it?

**Comment by marcglasberg** [comment]
@iuriegutu95 Thanks for the contribution.

@bauerj Hello Johann, could you please approve, or not, this PR? https://github.com/marcglasberg/i18n_extension/pull/78

**Comment by bauerj** [comment]
Yes, I will review shortly. Sorry for the delay, I should enable notifications for this repo.

**Comment by iuriegutu95** [comment]
@bauerj leaving a comment here as well as on PR #78 , in case you didn't turn on your notifications.
