### ISSUE TITLE
List available languages in phone

### ISSUE THREAD

**Issue by ManojMM026** [marcglasberg/i18n_extension#8]
This may be irrelevant but It will be great if we can have list of languages with codes from system.

**Comment by marcglasberg** [comment]
I'm not sure I understand what you mean. Could you please give more details?

**Comment by ManojMM026** [comment]
![72427734-67004a00-37b2-11ea-8673-7e3e32eacf7f](https://user-images.githubusercontent.com/2713390/72777065-60eaed00-3c3a-11ea-96ed-e5aa75b55e88.png)

These are the languages I have in phone, can we get the list of languages available in phone?

**Comment by hlemcke** [comment]
Have a look at devicelocale 0.2.1 for list of languages in phone.

Please do not integrate device specific methods into this package.

**Comment by marcglasberg** [comment]
I'm sorry, but I believe this is out of the scope for the `i18n_extension` package. To achieve what you ask it would need native code, and I'm not a native Android/iOS developer. So I couldn't do this even if I wanted.

I suggest you use this devicelocale package for that. Thank you.
