### ISSUE TITLE
Not compatible with flutter_launcher_icons >=0.9.0 

### ISSUE THREAD

**Issue by lozthiensu** [marcglasberg/i18n_extension#82]
For some reason I have to use flutter_launcher_icons> = 0.9.0. But this add-on is not at all compatible. Please release an update to fix this error

> Running "flutter pub get" in xxxkin...                  
> 
> Because i18n_extension >=4.0.1 depends on args ^1.6.0 and flutter_launcher_icons >=0.9.0 depends on args 2.0.0, i18n_extension >=4.0.1 is incompatible with flutter_launcher_icons >=0.9.0.
> So, because xxxkin depends on both i18n_extension ^4.0.3 and flutter_launcher_icons ^0.9.0, version solving failed.
> pub get failed (1; So, because xxxkin depends on both i18n_extension ^4.0.3 and flutter_launcher_icons ^0.9.0, version solving failed.)

**Comment by bauerj** [comment]
Hey,

please try to add

```
dependency_overrides:
  args: 2.0.0
```

to your pubspec as a workaround. Args 2 is not part of the current stable Flutter version so i18n_extension can not depend on it.

@marcglasberg would it make sense to change the version constraint to e.g. '>=1.6.0 <2.1'?
