### ISSUE TITLE
incompatible with build_runner ^2.0.1

### ISSUE THREAD

**Issue by vecharm** [marcglasberg/i18n_extension#84]
FINE: Resolving dependencies finished (1.6s).                           
ERR : Because build_runner >=2.0.0 depends on args ^2.0.0 and i18n_extension 4.0.3 depends on args ^1.6.0, build_runner >=2.0.0 is incompatible with i18n_extension 4.0.3.
    | And because no versions of i18n_extension match >4.0.3 <5.0.0, build_runner >=2.0.0 is incompatible with i18n_extension ^4.0.3.
    | So, because project depends on both i18n_extension ^4.0.3 and build_runner ^2.0.1, version solving failed.

**Comment by marcglasberg** [comment]
This couldn't be upgraded to args ^2.0.0 before because of flutter_driver was still in args 1.6.0. After Flutter 2.2 this could change., Closing this.
