### ISSUE TITLE
i18n_extension:getstrings does not work with Gettext importer

### ISSUE THREAD

**Issue by maxkreja** [marcglasberg/i18n_extension#88]
When exporting the string using `flutter pub run i18n_extension:getstrings`, the generated POT contain all keys sorted by context like this: 

```
msgctxt "./lib\\screens\\intro_screen.dart:147"
msgid "Some text"
msgstr ""
```

The Gettext importer doesn't import these strings, it just imports strings from the default content, which is empty if you generate PO files from the POT.

This makes working with this plugin harder, as it could be. I suggest adjusting the getstrings utility in a way that the strings are saved without their context because I think this will be faster. I might submit a pull request later today.

**Comment by marcglasberg** [comment]
@maxkreja the gettstrings was contributed by Johann Bauer.

@bauerj Could you please check this PR, when you have the time? Thank you!

**Comment by bauerj** [comment]
@marcglasberg I already did, please check the conversation in the PR. It looks good to me.
