### ISSUE TITLE
Bump analyzer to 2.0.0 to avoid breaking changes with Flutter 2.4.0-4.2.pre

### ISSUE THREAD

**Issue by nerder** [marcglasberg/i18n_extension#90]
As in the title there are breaking changes with `analyzer` which are blocking the code generation using `build_runner` by upgrade devs will not need to force the version using `dependencies_overrides`

*flutter --version*
```
Flutter 2.4.0-4.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision f18b9281c2 (5 days ago) • 2021-07-22 14:08:30 -0700
Engine • revision 844c29f42a
Tools • Dart 2.14.0 (build 2.14.0-301.2.beta)
```

**Comment by marcglasberg** [comment]
Thank you both for the issue and the PR. I will accept the PR as soon as Flutter 2.4.0 goes to stable.

**Comment by nerder** [comment]
Hey @marcglasberg , seems like [Flutter 2.5.0 ](https://flutter.dev/docs/development/tools/sdk/releases) is in `stable` now. Can you please merge this now?

**Comment by marcglasberg** [comment]
@nerder Done.
