### ISSUE TITLE
Issue importing .po files, "Translation key is missing"

### ISSUE THREAD

**Issue by Namli1** [marcglasberg/i18n_extension#92]
When trying to import the .po files as described [here](https://github.com/marcglasberg/i18n_extension/issues/63#issuecomment-770056237), I get the message: 
```
➜ Translation key in 'en_GB' is missing: ...
```
 and nothing is translated.

### My main.dart
```dart 
class MyApp extends StatefulWidget {
  // This widget is the root of your application.
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Future<void>? loadAsync;

  @override
  Widget build(BuildContext context) {
    return AdaptiveTheme(
      light: ThemeData(brightness: Brightness.light),
      initial: AdaptiveThemeMode.system,
      builder: (theme, darkTheme) => MaterialApp(
        title: 'My app',
        theme: theme,
        darkTheme: darkTheme,
        localizationsDelegates: [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        supportedLocales: [
          const Locale('en'),
          const Locale('de'),
        ],
        home: FutureBuilder(
          future: loadAsync,
          builder: (BuildContext context, AsyncSnapshot<void> snapshot) {
            if (snapshot.connectionState == ConnectionState.done) {
              return I18n(child: NavigationScreen());
            }
            return Shimmer.fromColors(
                child: NavigationScreen(),
                baseColor: Theme.of(context).primaryColor,
                highlightColor: Theme.of(context).accentColor);
          },
        ),
        routes: {
          MapScreen.routeName: (context) => MapScreen(),
          AuthScreen.routeName: (context) => AuthScreen(),
        },
      ),
    );
  }

  @override
  void initState() {
    super.initState();
    loadAsync = MyI18n.loadTranslations();
  }
}
```
<details>
<summary>
My i18n.dart setup (like @bauerj's setup):
</summary>

### Just like [here](https://github.com/marcglasberg/i18n_extension/issues/63#issuecomment-768477303)

```dart
import 'package:i18n_extension/io/import.dart';

import 'package:i18n_extension/i18n_extension.dart';

class MyI18n {
  static TranslationsByLocale translations = Translations.byLocale("en_GB");

  static Future<void> loadTranslations() async {
    translations +=
        await GettextImporter().fromAssetDirectory("assets/locales");
  }
}

extension Localization on String {
  String get i18n => localize(this, MyI18n.translations);
  String plural(int value) => localizePlural(value, this, MyI18n.translations);
  String fill(List<Object> params) => localizeFill(this, params);
}
```
</details>

### The translated widget
```dart
import '../i18n.dart'; //Importing the i18n.dart file mentioned above ↑

Text(
    "Welcome back 👋!".i18n,
    textAlign: TextAlign.start,
),
```

### The .po file (named de.po)
```po
msgctxt "./lib/screens/dashboard_screen.dart:47"
msgid "Welcome back 👋!"
msgstr "Wilkommen zurück 👋!"
```

# The problem
I tried to do everything as described in issue #63, but I can't get it to work with the .po-files, I just keep on getting the message `➜ Translation key in 'en_GB' is missing:...`.
 
Does anyone know how to fix this, maybe @bauerj? 
I don't know if it's just my .po file that's the problem, because apart from that I tried to do everything just like in the [paperless_app](https://github.com/bauerj/paperless_app) repository from @bauerj.

<br />
PS: I really love this package, it's the best flutter package for translations, because it's so easy and it even supports .po files, that's awesome! 🥳

**Comment by bauerj** [comment]
Hey,

I just took a quick look at your code, but shouldn't it be `Welcome back 👋!".i18n`?

**Comment by Namli1** [comment]
Yes, you're totally right, but that was actually just my foolishness; that part got lost while copying, it did exist in the real code, the `flutter: ➜ Translation key in 'en_GB' is missing: "Welcome back 👋!"`-message still shows. (I edited my previous answer now). 
Thanks for the quick reply however!

**Comment by bauerj** [comment]
Do you have the entire project somewhere in GitHub?

Maybe you forgot the asset definition in your pubspec?

**Comment by Namli1** [comment]
Alright, after a bit of looking through the code, I found out what was causing these error messages:

## The problem
The code for importing .po files was updated in this repository, but it hasn't been published to pub.dev yet. The code in the import.po file in the package on pub.dev no longer works, it returns null right here (at least for me):
```dart
Map translations = gettext_parser.po.parse(source)["translations"][""];
```
On GitHub, this looks like this (this code works!):
https://github.com/marcglasberg/i18n_extension/blob/d2afa2e351a4f742e9b76814b5d6efc54fc30997/lib/io/import.dart#L70

## The solution
Well, the obvious solution would be to update the package on pub.dev, can anybody of you do that, @bauerj or @marcglasberg?

### Side note
I noticed that you shouldn't set language codes when using .po files, because the filename only reveals the language, not the country. If you do set a country code, you'll get errors like this:
```
➜ There are no translations in 'en_us' for "Categories"
```
This may be obvious, but for people like me, it would be helpful to note this in the docs :-). (Might submit a PR later, if that's okay)

**Comment by bauerj** [comment]
Thank you for your detailed analysis of the problem!

Indeed, this should be updated on pub.dev. Only @marcglasberg can do that.

**Comment by Namli1** [comment]
Perfect, I'm eagerly waiting for the update, so I can use this awesome package with all its features!
By the way, I submitted a PR to update the README to make the .po import part more clear: #93.
Thanks for your support @bauerj. I'll close this issue once the pub.dev package gets updated, if that's okay.

**Comment by marcglasberg** [comment]
Version 4.1.1 is published.

@Namli1 Please note we can't have `dart` after the 3 ticks that denote a code block, because the official `.md` editor for IntelliJ is full of bugs and one of them is that it unformats the code if you add `dart` there. So I have removed those from your PR. Thanks!
