### ISSUE TITLE
Support to phrase.com

### ISSUE THREAD

**Issue by augustorsouza** [marcglasberg/i18n_extension#94]
This lib is great but it doesn't support phrase.com i18n saas. Is it in your plans? This is something supported by intl, for example: https://phrase.com/blog/posts/how-to-internationalize-a-flutter-app/

**Comment by marcglasberg** [comment]
I believe it's phrase.com that supports `intl`, not the other way around. Just the same, `i18n_extension` cannot support phrase.com; they need to export their info in a way that `i18n_extension` understands.

i18n_extension understands simple `Map`s. So it's really very easy to create export/import tools. There is a `.PO` importer/exporter to i18n_extension, which was contributed by the community. Please check if phrase.com can export to `.PO`.
